-- Add order_number column to orders table with auto-increment starting from 1001
ALTER TABLE public.orders 
ADD COLUMN IF NOT EXISTS order_number BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1001);

-- Backfill existing orders if any
-- This assumes we want to assign numbers to existing orders in order of creation
DO $$
DECLARE
    r RECORD;
    n BIGINT := 1001;
BEGIN
    FOR r IN (SELECT id FROM public.orders ORDER BY created_at ASC) LOOP
        UPDATE public.orders SET order_number = n WHERE id = r.id;
        n := n + 1;
    END LOOP;
END $$;
